REM  FIBONACCI SEQUENCE GENERATOR
REM  RELEASED INTO THE PUBLIC DOMAIN

REM  SETUP THE VARIABLES -- COUNTER, CURRENT VALUE AND LAST VALUE
LET I = 0
LET X = 1
LET Y = 0

REM  DISPLAY THE CURRENT ITERATION AND VALUE
LABEL fiblabel
PRINT "FIB: "; I, X

REM  ADD THE LAST VALUE TO THE CURRENT VALUE WHILE SAVING THE CURRENT VALUE
REM  AS THE NEW LAST VALUE
LET Z = X
LET X = X + Y
LET Y = Z

REM  INCREMENTING THE ITERATOR AND ABORTING WHEN IT'S TIME
LET I = I + 1
IF I <= 10 GOTOL fiblabel
