#ifndef REX_JIT_TARGET
#define REX_JIT_TARGET
#include <system.h>
typedef struct {
	unsigned int WordSize;
	unsigned int NumberOfRegisters;
	char** RegisterNames;
	void (*InitCPUSubModule)(void);
	void (*CPUPushStack)(unsigned int);
	void (*CPUPopStack)(void);
	void (*CPUPopStackN)(unsigned int);
	void (*CPUPushRegister)(unsigned int);
	void (*CPUPopRegister)(unsigned int);
	void (*CPULoadRegister)(unsigned int, unsigned int);
	void (*CPUBitwiseXor)(unsigned int, unsigned int);
	void (*CPUBitwiseOr)(unsigned int, unsigned int);
	void (*CPUBitwiseAnd)(unsigned int, unsigned int);
	void (*CPUBitwiseShl)(unsigned int, unsigned int);
	void (*CPUBitwiseShr)(unsigned int, unsigned int);
	void (*CPUBitwiseRol)(unsigned int, unsigned int);
	void (*CPUBitwiseRor)(unsigned int, unsigned int);
	void (*CPUJump)(unsigned int);
	void (*CPUCompare)(unsigned int, unsigned int);
	void (*CPUCompareSigned)(unsigned int, unsigned int);
	void (*CPUJumpifEqual)(unsigned int);
	void (*CPUJumpifGreater)(unsigned int);
	void (*CPUJumpifLesser)(unsigned int);
	void (*CPUJumpifZero)(unsigned int); 
	void (*CPUPushFlags)(void);
	void (*CPUPopFlags)(void);
	void (*CPUCallProcedure)(unsigned int);
	void (*CPUExitProcedure)(unsigned int);
	void (*CPUStore8)(unsigned int, unsigned int);
	void (*CPUStore16)(unsigned int, unsigned int);
	void (*CPUStore32)(unsigned int, unsigned int);
	void (*CPULoad8)(unsigned int);
	void (*CPULoad16)(unsigned int);
	void (*CPULoad32)(unsigned int);
	void (*CPUAdd)(unsigned int, unsigned int);
	void (*CPUSub)(unsigned int, unsigned int);
	void (*CPUMul)(unsigned int, unsigned int);
	void (*CPUDiv)(unsigned int, unsigned int);
	void (*CPUIEEE754Add)(float, float);
	void (*CPUIEEE754Sub)(float, float);
	void (*CPUIEEE754Mul)(float, float);
	void (*CPUIEEE754Div)(float, float);
	void (*CPUComputeSine)(float);
	void (*CPUComputeCosine)(float);
	void (*CPUComputeTangent)(float);
	void (*CPUComputeInverseSine)(float);
	void (*CPUComputeInverseCosine)(float);
	void (*CPUComputeInverseTangent)(float);
	void (*CPUComputeHyperbolicSine)(float);
	void (*CPUComputeHyperbolicCosine)(float);
	void (*CPUComputeHyperbolicTangent)(float);
	void (*CPUComputeHyperbolicInverseSine)(float);
	void (*CPUComputeHyperbolicInverseCosine)(float);
	void (*CPUComputeHyperbolicInverseTangent)(float);
	void (*CPUComputeSqrt)(float);
	void (*CPUComputePow)(float);
	void (*CPUComputeMod)(unsigned int);
	void (*CPUComputeFloatMod)(float);
	void (*CPUComputeFloor)(float);
	void (*CPUComputeCeil)(float);
	void (*CPUComputeAbsoluteValue)(float);
	void (*CPUSetRegisterIfEqual)(unsigned int);
	void (*CPUSetRegisterIfNotEqual)(unsigned int);
	void (*CPUSetRegisterIfGreater)(unsigned int);
	void (*CPUSetRegisterIfLesser)(unsigned int);
} RX_TARGET_CPU;
typedef struct {
	void (*SyscallPutChar)(unsigned int);
	void (*SyscallPutString)(unsigned int);
	void (*SyscallGetChar)(void);
	void (*SyscallFileOpen)(unsigned int);
	void (*SyscallFileClose)(unsigned int);
	void (*SyscallFileRead)(unsigned int, unsigned int, unsigned int);
	void (*SyscallFileSeek)(unsigned int, unsigned int);
	void (*SyscallFileWrite)(unsigned int, unsigned int, unsigned int);
	void (*SyscallDispatchJob)(unsigned int);
} RX_TARGET_OS;
#endif
